#!/usr/local/bin/Rscript --no-site-file --no-init-file --no-restore

# --vanilla ==> --no-site-file --no-init-file --no-restore --no-environ
# thus the above reads the .Renviron file(s)

## required packages ==
# devtools::install_github("docopt/docopt.R")
# install.packages("httr")

## docopt.org ==
"Usage:
    gh-dl --user=<user> --pkg=<pkg> --path=<path>
    gh-dl -h | --help

Options:
    --user=<user>   Github username
    --pkg=<pkg>     R package name
    --path=<path>   Directory path to save tar.gz file
    -h, --help      Help

Example:
    gh-dl --user=rstudio --pkg=sparklyr --path=\"~/code/R/pkgs\"" -> doc

## download ==
opts <- docopt::docopt(doc)

pkg_path <- file.path(opts$path)

url <- paste0("https://api.github.com/repos/",
              opts$user, "/",
              opts$pkg, "/tarball")

# get CA path (if needed)
# store path to CA file in the .Renviron file, naming it HTTR_CAINFO
httr_cainfo <- Sys.getenv("HTTR_CAINFO")

if(httr_cainfo != "") {
  httr::set_config(httr::config(cainfo = httr_cainfo))
}
httr::GET(url, httr::write_disk(file.path(pkg_path, paste0(opts$pkg, ".tar.gz"))))

# vim:syntax=R
